# Generated by Django 6.0.5 on 2026-05-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_series_post_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_url',
            field=models.URLField(blank=True),
        ),
    ]
